repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.4
    hooks:
    -   id: clang-format
        args: ["-style=Google"]
        entry: .ci_tools/clang-format.sh -i
        'types_or': [c++, c]
