repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-xml
    -   id: check-yaml
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    -   id: mdformat
        args: ["--wrap", "80"]
        additional_dependencies:
        - mdformat-gfm
