repos:
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v15.0.4
    hooks:
    -   id: clang-format
        args: ["-style=Google"]
        entry: .ci_tools/clang-format.sh -i
        'types_or': [c++, c]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-xml
    -   id: check-yaml
-   repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
    -   id: mdformat
        args: ["--wrap", "80"]
        additional_dependencies:
        - mdformat-gfm
