name: build

on:
  push:
    branches: [ main develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.0
    - name: setup env
      run:
        source .ci_tools/setup_env.sh
    - name: build samples
      run: |
        export SAMPLE_CI_RESULT=0
        source .ci_tools/build_samples.sh
        source .ci_tools/run_samples.sh
        eval "[[ $SAMPLE_CI_RESULT == 0 ]]"

